-- ============================================================
-- Migration 020 : Auto-apprentissage
-- TABLE : filter_keywords (whitelist dynamique du filtre hors-sujet)
-- ============================================================

CREATE TABLE IF NOT EXISTS filter_keywords (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword text NOT NULL UNIQUE,
  domain text,
  added_by text DEFAULT 'manual',
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_filter_keywords_keyword ON filter_keywords(keyword);

-- Pré-remplir avec tous les mots-clés actuels de IMMO_KEYWORDS (route.ts)
INSERT INTO filter_keywords (keyword, domain, added_by) VALUES
  -- Bail / location
  ('bail', 'baux_habitation', 'manual'),
  ('loyer', 'baux_habitation', 'manual'),
  ('locataire', 'baux_habitation', 'manual'),
  ('bailleur', 'baux_habitation', 'manual'),
  ('location', 'baux_habitation', 'manual'),
  ('sous-louer', 'baux_habitation', 'manual'),
  ('sous-location', 'baux_habitation', 'manual'),
  ('congé', 'baux_habitation', 'manual'),
  ('expulsion', 'baux_habitation', 'manual'),
  ('dépôt de garantie', 'baux_habitation', 'manual'),
  ('depot de garantie', 'baux_habitation', 'manual'),
  ('préavis', 'baux_habitation', 'manual'),
  ('preavis', 'baux_habitation', 'manual'),
  ('trêve hivernale', 'baux_habitation', 'manual'),
  ('treve hivernale', 'baux_habitation', 'manual'),
  ('clause résolutoire', 'baux_habitation', 'manual'),
  ('irl', 'baux_habitation', 'manual'),
  ('quittance', 'baux_habitation', 'manual'),
  ('état des lieux', 'baux_habitation', 'manual'),
  ('etat des lieux', 'baux_habitation', 'manual'),
  ('logement', 'baux_habitation', 'manual'),
  ('appartement', 'baux_habitation', 'manual'),
  ('propriétaire', 'baux_habitation', 'manual'),
  ('louer', 'baux_habitation', 'manual'),
  ('locatif', 'baux_habitation', 'manual'),
  ('résiliation', 'baux_habitation', 'manual'),
  ('renouvellement du bail', 'baux_habitation', 'manual'),
  -- Bail — situations spéciales
  ('squat', 'baux_habitation', 'manual'),
  ('squatteur', 'baux_habitation', 'manual'),
  ('occupation illicite', 'baux_habitation', 'manual'),
  ('colocation', 'baux_habitation', 'manual'),
  ('caution solidaire', 'baux_habitation', 'manual'),
  ('garantie visale', 'baux_habitation', 'manual'),
  ('gli', 'baux_habitation', 'manual'),
  ('assurance loyers impayés', 'baux_habitation', 'manual'),
  ('insalubrité', 'baux_habitation', 'manual'),
  ('logement indigne', 'baux_habitation', 'manual'),
  ('habitat indigne', 'baux_habitation', 'manual'),
  ('meublé tourisme', 'baux_habitation', 'manual'),
  -- Copropriété
  ('copropriété', 'copropriete', 'manual'),
  ('copropriete', 'copropriete', 'manual'),
  ('syndic', 'copropriete', 'manual'),
  ('assemblée générale', 'copropriete', 'manual'),
  ('assemblee generale', 'copropriete', 'manual'),
  ('charges de copropriété', 'copropriete', 'manual'),
  ('tantièmes', 'copropriete', 'manual'),
  ('tantiemes', 'copropriete', 'manual'),
  ('parties communes', 'copropriete', 'manual'),
  ('règlement de copropriété', 'copropriete', 'manual'),
  ('syndicat des copropriétaires', 'copropriete', 'manual'),
  ('lot de copropriété', 'copropriete', 'manual'),
  -- Agent immobilier / mandat
  ('agent immobilier', 'agent_immobilier', 'manual'),
  ('mandat', 'agent_immobilier', 'manual'),
  ('honoraires', 'agent_immobilier', 'manual'),
  ('hoguet', 'agent_immobilier', 'manual'),
  ('carte t', 'agent_immobilier', 'manual'),
  ('commission', 'agent_immobilier', 'manual'),
  ('agence immobilière', 'agent_immobilier', 'manual'),
  ('agence immobiliere', 'agent_immobilier', 'manual'),
  ('négociateur', 'agent_immobilier', 'manual'),
  ('negociateur', 'agent_immobilier', 'manual'),
  ('devoir de conseil', 'agent_immobilier', 'manual'),
  ('compromis', 'vente_immobiliere', 'manual'),
  ('promesse de vente', 'vente_immobiliere', 'manual'),
  -- Transactions
  ('vente', 'vente_immobiliere', 'manual'),
  ('acheteur', 'vente_immobiliere', 'manual'),
  ('vendeur', 'vente_immobiliere', 'manual'),
  ('notaire', 'vente_immobiliere', 'manual'),
  ('frais de notaire', 'vente_immobiliere', 'manual'),
  ('avant-contrat', 'vente_immobiliere', 'manual'),
  ('vice caché', 'vente_immobiliere', 'manual'),
  ('vice cache', 'vente_immobiliere', 'manual'),
  ('rétractation', 'vente_immobiliere', 'manual'),
  ('retractation', 'vente_immobiliere', 'manual'),
  ('condition suspensive', 'vente_immobiliere', 'manual'),
  ('acte authentique', 'vente_immobiliere', 'manual'),
  ('sru', 'vente_immobiliere', 'manual'),
  ('plus-value', 'fiscalite', 'manual'),
  ('droits de mutation', 'vente_immobiliere', 'manual'),
  ('préemption', 'urbanisme', 'manual'),
  ('preemption', 'urbanisme', 'manual'),
  -- Diagnostics
  ('diagnostic', 'diagnostics', 'manual'),
  ('dpe', 'diagnostics', 'manual'),
  ('amiante', 'diagnostics', 'manual'),
  ('plomb', 'diagnostics', 'manual'),
  ('termites', 'diagnostics', 'manual'),
  ('erp', 'diagnostics', 'manual'),
  ('carrez', 'diagnostics', 'manual'),
  ('audit énergétique', 'diagnostics', 'manual'),
  ('audit energetique', 'diagnostics', 'manual'),
  ('passoire thermique', 'diagnostics', 'manual'),
  ('classe énergétique', 'diagnostics', 'manual'),
  ('mérule', 'diagnostics', 'manual'),
  ('radon', 'diagnostics', 'manual'),
  ('diagnostiqueur', 'diagnostics', 'manual'),
  ('dpe erroné', 'diagnostics', 'manual'),
  ('dpe opposable', 'diagnostics', 'manual'),
  ('classe g', 'diagnostics', 'manual'),
  ('classe f', 'diagnostics', 'manual'),
  -- Urbanisme / construction
  ('urbanisme', 'urbanisme', 'manual'),
  ('permis de construire', 'urbanisme', 'manual'),
  ('plu', 'urbanisme', 'manual'),
  ('zan', 'urbanisme', 'manual'),
  ('vefa', 'urbanisme', 'manual'),
  ('décennale', 'construction', 'manual'),
  ('decennale', 'construction', 'manual'),
  ('malfaçon', 'construction', 'manual'),
  ('travaux', 'construction', 'manual'),
  ('construction', 'construction', 'manual'),
  ('déclaration préalable', 'urbanisme', 'manual'),
  ('lotissement', 'urbanisme', 'manual'),
  ('zone inondable', 'urbanisme', 'manual'),
  ('ppri', 'urbanisme', 'manual'),
  ('monument historique', 'urbanisme', 'manual'),
  -- Fiscalité immo
  ('sci', 'fiscalite', 'manual'),
  ('ifi', 'fiscalite', 'manual'),
  ('pinel', 'fiscalite', 'manual'),
  ('denormandie', 'fiscalite', 'manual'),
  ('déficit foncier', 'fiscalite', 'manual'),
  ('deficit foncier', 'fiscalite', 'manual'),
  ('lmnp', 'fiscalite', 'manual'),
  ('revenus fonciers', 'fiscalite', 'manual'),
  ('taxe foncière', 'fiscalite', 'manual'),
  ('taxe fonciere', 'fiscalite', 'manual'),
  -- Autres domaines
  ('viager', 'viager_demembrement', 'manual'),
  ('usufruit', 'viager_demembrement', 'manual'),
  ('démembrement', 'viager_demembrement', 'manual'),
  ('demembrement', 'viager_demembrement', 'manual'),
  ('nue-propriété', 'viager_demembrement', 'manual'),
  ('bail commercial', 'bail_commercial', 'manual'),
  ('fonds de commerce', 'bail_commercial', 'manual'),
  ('crédit immobilier', 'vente_immobiliere', 'manual'),
  ('credit immobilier', 'vente_immobiliere', 'manual'),
  ('immobilier', 'autres', 'manual'),
  ('immeuble', 'autres', 'manual'),
  ('bien immobilier', 'autres', 'manual'),
  ('terrain', 'autres', 'manual'),
  -- Successions / protection / famille
  ('tutelle', 'vente_immobiliere', 'manual'),
  ('curatelle', 'vente_immobiliere', 'manual'),
  ('indivision', 'vente_immobiliere', 'manual'),
  ('succession', 'vente_immobiliere', 'manual'),
  ('donation', 'vente_immobiliere', 'manual'),
  ('héritage', 'vente_immobiliere', 'manual'),
  ('héritier', 'vente_immobiliere', 'manual'),
  ('héritiers', 'vente_immobiliere', 'manual'),
  ('partage', 'vente_immobiliere', 'manual'),
  ('mandat de protection future', 'vente_immobiliere', 'manual'),
  ('divorce', 'vente_immobiliere', 'manual'),
  ('liquidation communauté', 'vente_immobiliere', 'manual'),
  ('séparation de biens', 'vente_immobiliere', 'manual'),
  ('bien propre', 'vente_immobiliere', 'manual'),
  ('bien commun', 'vente_immobiliere', 'manual'),
  ('donation-partage', 'vente_immobiliere', 'manual'),
  ('pacte de famille', 'vente_immobiliere', 'manual'),
  ('indivision successorale', 'vente_immobiliere', 'manual'),
  -- Litiges immobiliers
  ('assignation', 'litiges', 'manual'),
  ('référé', 'litiges', 'manual'),
  ('mise en demeure', 'litiges', 'manual'),
  ('commissaire de justice', 'litiges', 'manual'),
  ('prescription', 'litiges', 'manual'),
  ('forclusion', 'litiges', 'manual'),
  ('expertise judiciaire', 'litiges', 'manual'),
  ('astreinte', 'litiges', 'manual'),
  ('saisie immobilière', 'litiges', 'manual'),
  -- Urbanisme - certificat
  ('certificat d''urbanisme', 'urbanisme', 'manual'),
  -- Servitudes
  ('servitude', 'servitudes', 'manual'),
  ('mitoyenneté', 'servitudes', 'manual')
ON CONFLICT (keyword) DO NOTHING;
